#!/bin/bash
# Tool Call Logger
# Logs tool calls to session context for investigation protocol validation
#
# Usage:
#   .claude/scripts/log-tool-call.sh <tool> <args...>
#
# Examples:
#   .claude/scripts/log-tool-call.sh Read apps/api/src/domains/banking/routes.ts
#   .claude/scripts/log-tool-call.sh Grep "pattern" apps/
#   .claude/scripts/log-tool-call.sh Write apps/web/src/app/page.tsx

SESSION_LOG=".claude/.session-context.log"

# Ensure directory exists
mkdir -p "$(dirname "$SESSION_LOG")"

# Create log file if doesn't exist
if [ ! -f "$SESSION_LOG" ]; then
  echo "# Session Context Log - $(date -u +"%Y-%m-%dT%H:%M:%SZ")" > "$SESSION_LOG"
  echo "# Auto-generated by tool-call logging" >> "$SESSION_LOG"
  echo "" >> "$SESSION_LOG"
fi

# Log the tool call
TIMESTAMP=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
echo "[$TIMESTAMP] $*" >> "$SESSION_LOG"