import React from 'react';
import { Document, Page, Text, View } from '@react-pdf/renderer';
import { renderToBuffer } from '@react-pdf/renderer';
import { AccountingError } from '../errors';
import type { BalanceSheetReport, ReportLineItem } from '../services/report.service';
import {
  reportStyles as s,
  truncate,
  formatCentsForPdf,
  formatDateForPdf,
  countLineItems,
  PDF_MAX_ENTRIES,
  PDF_TIMEOUT_MS,
} from './shared-styles';

/**
 * Generate Balance Sheet PDF
 */
export async function generateBalanceSheetPdf(report: BalanceSheetReport): Promise<Buffer> {
  const allItems = [
    ...(report.assets?.items || []),
    ...(report.liabilities?.items || []),
    ...(report.equity?.items || []),
  ];
  const lineItemCount = countLineItems(allItems);

  if (lineItemCount > PDF_MAX_ENTRIES) {
    throw new AccountingError(
      `Report too large for PDF export (${lineItemCount} entries exceed ${PDF_MAX_ENTRIES} limit). Use CSV export instead.`,
      'PDF_TOO_LARGE',
      400
    );
  }

  let timeoutHandle: ReturnType<typeof setTimeout>;
  const timeoutPromise = new Promise<never>((_, reject) => {
    timeoutHandle = setTimeout(() => reject(new AccountingError('PDF generation timed out', 'PDF_TIMEOUT', 408)), PDF_TIMEOUT_MS);
  });

  const pdfDoc = (
    <Document>
      <Page size="A4" style={s.page}>
        {/* Header */}
        <View style={s.header}>
          <Text style={s.headerTitle}>Balance Sheet</Text>
          <Text style={s.headerSubtitle}>{truncate(report.entityName, 100)}</Text>
          <Text style={s.headerDate}>As of {formatDateForPdf(report.asOfDate)}</Text>
          <Text style={s.headerDate}>Currency: {report.currency}</Text>
        </View>

        {/* Unbalanced Warning */}
        {!report.isBalanced && (
          <View style={s.warningBox}>
            <Text style={s.warningText}>
              WARNING: Balance sheet does not balance. Assets ({formatCentsForPdf(report.totalAssets, report.currency)}) ≠
              Liabilities + Equity ({formatCentsForPdf(report.totalLiabilitiesAndEquity, report.currency)})
            </Text>
          </View>
        )}

        {/* Assets */}
        <View>
          <Text style={s.sectionHeader}>Assets</Text>
          <LineItems items={report.assets?.items || []} currency={report.currency} />
          <View style={s.totalRow}>
            <Text style={s.totalLabel}>Total Assets</Text>
            <Text style={s.totalValue}>{formatCentsForPdf(report.totalAssets, report.currency)}</Text>
          </View>
        </View>

        {/* Liabilities */}
        <View>
          <Text style={s.sectionHeader}>Liabilities</Text>
          <LineItems items={report.liabilities?.items || []} currency={report.currency} />
          <View style={s.totalRow}>
            <Text style={s.totalLabel}>Total Liabilities</Text>
            <Text style={s.totalValue}>{formatCentsForPdf(report.liabilities?.total || 0, report.currency)}</Text>
          </View>
        </View>

        {/* Equity */}
        <View>
          <Text style={s.sectionHeader}>Equity</Text>
          <LineItems items={report.equity?.items || []} currency={report.currency} />

          {/* Retained Earnings */}
          <View style={s.row}>
            <Text style={s.rowLabel}>Retained Earnings (Prior Years)</Text>
            <Text style={s.rowValue}>{formatCentsForPdf(report.retainedEarnings.priorYears, report.currency)}</Text>
          </View>
          <View style={s.row}>
            <Text style={s.rowLabel}>Net Income (Current Year)</Text>
            <Text style={s.rowValue}>{formatCentsForPdf(report.retainedEarnings.currentYear, report.currency)}</Text>
          </View>

          <View style={s.totalRow}>
            <Text style={s.totalLabel}>Total Equity</Text>
            <Text style={s.totalValue}>{formatCentsForPdf(report.equity?.total || 0, report.currency)}</Text>
          </View>
        </View>

        {/* Grand Total */}
        <View style={s.grandTotalRow}>
          <Text style={s.grandTotalLabel}>Total Liabilities &amp; Equity</Text>
          <Text style={s.grandTotalValue}>
            {formatCentsForPdf(report.totalLiabilitiesAndEquity, report.currency)}
          </Text>
        </View>

        {/* Footer */}
        <View style={s.footer} fixed>
          <Text style={s.footerText}>Generated by Akount on {new Date().toLocaleDateString('en-CA')}</Text>
          <Text style={s.footerText}>Confidential</Text>
        </View>
      </Page>
    </Document>
  );

  try {
    const buffer = await Promise.race([
      renderToBuffer(pdfDoc),
      timeoutPromise,
    ]);
    return Buffer.from(buffer);
  } finally {
    clearTimeout(timeoutHandle!);
  }
}

function LineItems({ items, currency }: { items: ReportLineItem[]; currency: string }) {
  return (
    <View>
      {items.map((item, idx) => (
        <View key={idx} style={[s.row, { paddingLeft: 4 + item.depth * 12 }]}>
          <Text style={[s.rowLabel, item.isSubtotal ? { fontFamily: 'Helvetica-Bold' } : {}]}>
            {truncate(item.code, 10)} - {truncate(item.name, 60)}
          </Text>
          <Text style={s.rowValue}>{formatCentsForPdf(item.balance, currency)}</Text>
        </View>
      ))}
    </View>
  );
}
