import React from 'react';
import { Document, Page, Text, View } from '@react-pdf/renderer';
import { renderToBuffer } from '@react-pdf/renderer';
import { AccountingError } from '../errors';
import type { CashFlowReport } from '../services/report.service';
import {
  reportStyles as s,
  truncate,
  formatCentsForPdf,
  formatDateForPdf,
  countLineItems,
  PDF_MAX_ENTRIES,
  PDF_TIMEOUT_MS,
} from './shared-styles';

/**
 * Generate Cash Flow Statement PDF
 */
export async function generateCashFlowPdf(report: CashFlowReport): Promise<Buffer> {
  const allItems = [
    ...(report.operating?.items || []),
    ...(report.investing?.items || []),
    ...(report.financing?.items || []),
  ];
  const lineItemCount = countLineItems(allItems);

  if (lineItemCount > PDF_MAX_ENTRIES) {
    throw new AccountingError(
      `Report too large for PDF export (${lineItemCount} entries exceed ${PDF_MAX_ENTRIES} limit). Use CSV export instead.`,
      'PDF_TOO_LARGE',
      400
    );
  }

  let timeoutHandle: ReturnType<typeof setTimeout>;
  const timeoutPromise = new Promise<never>((_, reject) => {
    timeoutHandle = setTimeout(() => reject(new AccountingError('PDF generation timed out', 'PDF_TIMEOUT', 408)), PDF_TIMEOUT_MS);
  });

  const pdfDoc = (
    <Document>
      <Page size="A4" style={s.page}>
        {/* Header */}
        <View style={s.header}>
          <Text style={s.headerTitle}>Cash Flow Statement</Text>
          <Text style={s.headerSubtitle}>{truncate(report.entityName, 100)}</Text>
          <Text style={s.headerDate}>
            {formatDateForPdf(report.startDate)} to {formatDateForPdf(report.endDate)}
          </Text>
          <Text style={s.headerDate}>Currency: {report.currency}</Text>
        </View>

        {/* Operating Activities */}
        <View>
          <Text style={s.sectionHeader}>Operating Activities</Text>
          <View style={s.row}>
            <Text style={[s.rowLabel, { fontFamily: 'Helvetica-Bold' }]}>Net Income</Text>
            <Text style={s.rowValue}>{formatCentsForPdf(report.netIncome, report.currency)}</Text>
          </View>
          <ActivityItems items={report.operating?.items || []} currency={report.currency} />
          <View style={s.totalRow}>
            <Text style={s.totalLabel}>Cash from Operations</Text>
            <Text style={s.totalValue}>{formatCentsForPdf(report.operating?.total || 0, report.currency)}</Text>
          </View>
        </View>

        {/* Investing Activities */}
        <View>
          <Text style={s.sectionHeader}>Investing Activities</Text>
          <ActivityItems items={report.investing?.items || []} currency={report.currency} />
          <View style={s.totalRow}>
            <Text style={s.totalLabel}>Cash from Investing</Text>
            <Text style={s.totalValue}>{formatCentsForPdf(report.investing?.total || 0, report.currency)}</Text>
          </View>
        </View>

        {/* Financing Activities */}
        <View>
          <Text style={s.sectionHeader}>Financing Activities</Text>
          <ActivityItems items={report.financing?.items || []} currency={report.currency} />
          <View style={s.totalRow}>
            <Text style={s.totalLabel}>Cash from Financing</Text>
            <Text style={s.totalValue}>{formatCentsForPdf(report.financing?.total || 0, report.currency)}</Text>
          </View>
        </View>

        {/* Cash Summary */}
        <View style={{ marginTop: 16 }}>
          <View style={s.row}>
            <Text style={s.rowLabel}>Opening Cash Balance</Text>
            <Text style={s.rowValue}>{formatCentsForPdf(report.openingCash, report.currency)}</Text>
          </View>
          <View style={s.row}>
            <Text style={s.rowLabel}>Net Cash Change</Text>
            <Text style={s.rowValue}>{formatCentsForPdf(report.netCashChange, report.currency)}</Text>
          </View>
          <View style={s.grandTotalRow}>
            <Text style={s.grandTotalLabel}>Closing Cash Balance</Text>
            <Text style={s.grandTotalValue}>{formatCentsForPdf(report.closingCash, report.currency)}</Text>
          </View>
        </View>

        {/* Footer */}
        <View style={s.footer} fixed>
          <Text style={s.footerText}>Generated by Akount on {new Date().toLocaleDateString('en-CA')}</Text>
          <Text style={s.footerText}>Confidential</Text>
        </View>
      </Page>
    </Document>
  );

  try {
    const buffer = await Promise.race([
      renderToBuffer(pdfDoc),
      timeoutPromise,
    ]);
    return Buffer.from(buffer);
  } finally {
    clearTimeout(timeoutHandle!);
  }
}

function ActivityItems({ items, currency }: { items: Array<{ name: string; balance: number }>; currency: string }) {
  return (
    <View>
      {items.map((item, idx) => (
        <View key={idx} style={[s.row, { paddingLeft: 16 }]}>
          <Text style={s.rowLabel}>{truncate(item.name, 60)}</Text>
          <Text style={s.rowValue}>{formatCentsForPdf(item.balance, currency)}</Text>
        </View>
      ))}
    </View>
  );
}
